-- Assuming postgres
CREATE TABLE funds (
    id BIGSERIAL PRIMARY KEY,
    fund_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    fund_name VARCHAR(100) NOT NULL,
    fund_manager_name VARCHAR(100) NOT NULL,
    fund_description TEXT,
    fund_nav NUMERIC(20,2) DEFAULT NULL,
    fund_creation_date DATE NOT NULL,
    fund_performance NUMERIC(10,2),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fund_performance_history (
    id BIGSERIAL PRIMARY KEY,
    fund_id UUID NOT NULL REFERENCES funds(fund_id) ON DELETE CASCADE,
    performance NUMERIC(10,2) NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fund_transactions (
    id BIGSERIAL PRIMARY KEY,
    fund_id UUID NOT NULL REFERENCES funds(fund_id) ON DELETE CASCADE,
    transaction_type VARCHAR(50) NOT NULL,  -- e.g., 'investment', 'withdrawal'
    amount NUMERIC(20,2) NOT NULL,
    transaction_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
